[fix-accidental-assignment] Use comparison instead of destructive assignment
I found this when working on the CI, running, see
https://builds.sr.ht/~krobelus/job/388884 which runs

	CC=clang TIG_BUILD=config.make tools/travis.sh

The warning from clang was:

	src/diff.c:377:27: error: converting the enum constant to a boolean [-Werror,-Wint-in-bool-context]
	                   (type = LINE_DEFAULT ||