[fix-accidental-assignment] Fix, use comparison instead of destructive assignment
I found this when working on CI, running 
	CC=clang TIG_BUILD=config.make tools/travis.sh
in the CI, see https://builds.sr.ht/~krobelus/job/388884

The warning from clang was:

src/diff.c:377:27: error: converting the enum constant to a boolean [-Werror,-Wint-in-bool-context]
                   (type = LINE_DEFAULT ||